version: "3"

services:
  redis:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  shallwe:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis