spring:
  profiles:
    group:
      local:
        - local
        - redis
      dev:
        - dev
        - rds
        - redis
      test:
        - test
        - rds
        - redis
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: test