spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: redis
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace